### ISSUE TITLE
Go 1.18 requires go.mod file (Unable to compile)

### ISSUE THREAD

**Issue by samip5** [annttu/latenssi-go#1]
Running make in the repository results in a failure.

```
go get  github.com/op/go-logging
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
make: *** [deps] Error 1
```

**Comment by samip5** [comment]
Doesn't seem to work with Go 1.9 either:

```
go get  github.com/op/go-logging
go get  google.golang.org/grpc
# google.golang.org/grpc/internal/credentials
src/google.golang.org/grpc/internal/credentials/spiffe.go:37:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
src/google.golang.org/grpc/internal/credentials/spiffe.go:46:24: cert.URIs undefined (type *x509.Certificate has no field or method URIs)
src/google.golang.org/grpc/internal/credentials/spiffe.go:50:26: cert.URIs undefined (type *x509.Certificate has no field or method URIs)
src/google.golang.org/grpc/internal/credentials/spiffe.go:68:14: cert.URIs undefined (type *x509.Certificate has no field or method URIs)
# golang.org/x/net/http2
src/golang.org/x/net/http2/client_conn_pool.go:302:6: undefined: errors.Is
src/golang.org/x/net/http2/server.go:240:72: undefined: tls.VersionTLS13
src/golang.org/x/net/http2/transport.go:417:30: undefined: errors.Is
src/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
src/golang.org/x/net/http2/transport.go:2099:5: undefined: errors.Is
src/golang.org/x/net/http2/transport.go:2103:5: undefined: errors.Is
src/golang.org/x/net/http2/transport.go:2107:5: undefined: errors.Is
# google.golang.org/grpc/status
src/google.golang.org/grpc/status/status.go:128:5: undefined: errors.Is
src/google.golang.org/grpc/status/status.go:131:5: undefined: errors.Is
make: *** [deps] Error 2
```

**Comment by annttu** [comment]
Newest version should work with go >= 1.17.
